### ISSUE TITLE
Could not get the value.

### ISSUE THREAD

**Issue by SumeetMourya** [orale-tv/flutter_true_time#3]
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(You must call init before any call to now, The connection timed out., null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
<asynchronous suspension>
#2      TrueTime.now (package:true_time/true_time.dart:41:55)
<asynchronous suspension>

**Comment by a1eem** [comment]
@SumeetMourya ntp server used in given package is not working. I tried time.google.com as ntp server. it worked. But I had to use true_time.dart file instead of package. However, I proposed changes to author.

**Comment by pablo-co** [comment]
@a1eem thank you for jumping in! For some reason I wasn't aware of this issue. If I understand correctly the default "ntp.google.com" server isn't working right? You can change this when calling [init](https://github.com/orale-tv/flutter_true_time/blob/005fb75c1ccfa66a192f1e22894da3102868d6e3/lib/true_time.dart#L18) (although it is a NoOp in iOS as it is not supported by the TrueTime library).

I will update the package in the weekend to change the default NTP server :+1: .

**Comment by a1eem** [comment]
@pablo-co oh thank you so much for telling me about `init`. I completely forgot about setting ntp parameter when calling `init`.

**Comment by SumeetMourya** [comment]
@a1eem, thank you for answering the question and drill down towards the root cause of this issue.
But I am still having the same problem. 
I tried with  below code.

```

void main() => runApp(new MyApp2());
class MyApp2 extends StatefulWidget {
@override
  _MyAppState2 createState() => new _MyAppState2();
}

class _MyAppState2 extends State<MyApp2> {
  bool _initialized = false;
  DateTime _currentTime;

@override
  initState() {
    super.initState();
    _initPlatformState();
  }

  _initPlatformState() async {
    bool initialized = await TrueTime.init(ntpServer: 'time.google.com');
    setState(() {
      _initialized = initialized;
    });
    _updateCurrentTime();
  }

  _updateCurrentTime() async {
      DateTime now = await TrueTime.now ( );
      setState ( ( ) {
        _currentTime = now;
      } );
  }

  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new Scaffold(
        floatingActionButton: new FloatingActionButton(
          tooltip: 'Get current time',
          child: new Icon(Icons.timer),
          onPressed: _updateCurrentTime,
        ),
        appBar: new AppBar(
          title: new Text('Example TrueTime app'),
        ),
        body: new Column(
          children: <Widget>[
            new Text('TrueTime is initialized: $_initialized\n'),
            new Text('Current Time: $_currentTime\n'),
          ],
        ),
      ),
    );
  }
}
```

**Comment by a1eem** [comment]
@SumeetMourya It would be better for us to identify the problem if you post detailed Error. As I mentioned earlier, I had to use `true_time.dart` file and put `print(e)` in `catch block` of `init `to get the problem. You can do that too and paste stack trace here, if you dont understand the problem on your own.

**Comment by a1eem** [comment]
@pablo-co while you are updating ntp-server, can you please update code with `print(e)` in catch block before returning false. Thanks

**Comment by SumeetMourya** [comment]
@a1eem 
here is the error: 

```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(You must call init before any call to now, The connection timed out., null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
<asynchronous suspension>
#2      TrueTime.now (package:true_time/true_time.dart:41:55)
<asynchronous suspension>
#3      _MyAppState2._updateCurrentTime (package:booking/main.dart:170:37)
<asynchronous suspension>
#4      _MyAppState2._initPlatformState (package:booking/main.dart:166:5)
<asynchronous suspension>
#5      _MyAppState2.initState (package:booking/main.dart:158:5)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:58)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
#9      Element.updateChild (package<…>
```

**Comment by a1eem** [comment]
@SumeetMourya this is output of your class. Please do these steps:
1. Copy true_time.dart from this package to your project
2. Put print(e) in your copied true_time.dart file in catch block
3. Use copied true_time.dart file in your code and remove true_time package from your project (temporarily)
4. Execute code and then analyse what print(e) gives you.

Please note that, if your code works with copied true_time.dart file then you must put license of author in your project.

**Comment by SumeetMourya** [comment]
@a1eem:
I got this error in catch block.
flutter: MissingPluginException(No implementation found for method init on channel true_time)

Can you help me how to fix it?

**Comment by pablo-co** [comment]
Let me look into this! Will keep you posted on any updates!

**Comment by a1eem** [comment]
@SumeetMourya I also got this error when I tried to custom implement `true_time.dart`, but after using `time.google.com` as `ntpServer` parameter with `true_time package` (refer to pablo-co first comment) this error was gone.

**Comment by mnesarco** [comment]
I have problems in flutter to get init to work out of the box, but I have found this inconsistent behavior:

TrueTime.init() => Sometimes work, sometimes don't
TrueTime.init(ntpServer: "time.google.com") => Sometimes work, sometimes don't
TrueTime.init(ntpServer: "time1.google.com") => Sometimes work, sometimes don't

Probably what I need is a list of ntp servers and a retry mechanism, but I wonder how it will work on IOS.

**Comment by CoreyCole** [comment]
FWIW the other [ntp package](https://pub.dev/documentation/ntp/latest/) uses `pool.ntp.org`
